config/routes.rb
Rails.application.routes.draw do

  #get 'menu/index'
  #get '/intro' => 'menu#intro'
  get '/contact' => 'menu#contact'
  get '/about' => 'menu#about'
  get '/content' => 'menu#content'
  get '/how_it_works' => 'menu#how_it_works'
  resources :definitions
  resources :stories
  resources :emoquestions do

  member do
    
    get 'success'
    get 'failure'
    post 'check'
    get 'failed'
    
  end
end

  
  root 'menu#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/definition.rb
class Definition < ApplicationRecord
end

app/models/emoquestion.rb
class Emoquestion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController

	def show
		  #@definition  = Definition.find_by(entry: params[:id])

		  render params[:id]
	end	
end

app/controllers/emoquestions_controller.rb
class EmoquestionsController < ApplicationController

    def index
      @emoquestions = Emoquestion.all
    end

   def new
   end

   def how_it_works
      render 'how_it_works.html'   
   end 

   def create
     @emoquestion = Emoquestion.new(emoquestion_params)
	   @emoquestion.save
	   redirect_to @emoquestion
    end
  
   def show

    if params[:score] == nil

       params[:score] = 0

    end  

    begin
        
        @emoquestion = Emoquestion.find(params[:id])
        tmp = @emoquestion.question.split(' ')

        create_link = ->(x, y) { '<a href="../definitions/' + x + '"' + ' class="dictionary_links"' + '>' + y + '</a>' }

        tmp = tmp.map { |elem| 

          if elem[0..1] == '&&'

                  elem[2..-1]

          elsif  elem[0..1]  == '$$'

               elem = elem.split('_')

               create_link.call(elem[1], elem[0][2..-1])

           


              else create_link.call(elem, elem)

          end  

        }

        @emoquestion.question =  tmp.join("") 
        #<a href="https://www.w3schools.com/html/">Visit our HTML tutorial</a> 

        #render plain: @emoquestion.question
    
    end   

    rescue
      begin

      if Integer(params[:id]) == Emoquestion.last.id + 1
      
        redirect_to :action => "index"

      else Integer(params[:id]) > Emoquestion.last.id + 1

        render plain: 'this ID is way too high' 

    end

   rescue
          
          render plain: 'something went wrong' 

    end

  end    
      
      
   

  def check

    question_id = Integer(params[:emoquestion]['question_id']) 
    question = params[:emoquestion]['question_body']
    answ =  Integer(params[:emoquestion]['answer'])
    answer = Emoquestion.find(question_id).is_correct
    #render plain: params
    if answ == answer

      redirect_to :action => "success", id: question_id, score: params[:emoquestion]['score']

    else
    
    redirect_to :action => "failure", id: question_id, true_answer: answer, score: params[:emoquestion]['score'], question_body: question
  end
end



def success
     
    next_question_id = Integer(params[:id]) + 1

    redirect_to :action => "show", id: next_question_id, score: params[:score]

end

def failure
  
  next_question_id = Integer(params[:id]) + 1
  new_score = Integer(params[:score]) + 1
  #render plain: params[:question_body]

  redirect_to :action => "failed", id: Integer(params[:id]), next_question_id: next_question_id, true_answer: params[:answer], score: new_score, question_body: params[:question_body]  

end

def failed

  answer = Emoquestion.find(params[:id]).question

  
  is_correct = Emoquestion.find(params[:id]).is_correct

  tmp = ''

  params[:score] = [Integer(params[:score]), 20].min
    
  (1..Integer(params[:score])).each do |i|  tmp += '😿' end

  params['cats'] = tmp.encode("UTF-8")

  #render plain: params[:question_body]

  tmp = params[:question_body]
  tmp = tmp.gsub! '../', '../../'

  if is_correct == 1

    params['message'] =  "[" + tmp + "]" + ' is correct'

  else 
    
    params['message'] =  "[ "+ tmp + "]" + ' is not correct'

  end
    
end


private
 def emoquestion_params
   params.require(:emoquestion).permit(:question, :is_correct)
 end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index

  	render 'index.html'
  end

  def intro
  	render 'intro.html'
  end

  def contact
  	render 'contact.html'
  end

  def about
  	render 'about.html'
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  def show
  	#render plain: params
  	render  'stories/' + params[:id]
  end

  def intro
      render 'intro'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/helpers/emoquestions_helper.rb
module EmoquestionsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/definitions/show.html.erb
<head>

<style>
body {
  background-color: lightblue;
}

a {
	
	color: black;
	text-decoration: none;

}


.onomatopea {

    font-weight: normal;
	font-style: italic;
	
}

.next{

	text-align: right;
	margin-right : 10%;
	font-size: 130%;
	
}


.centered_bold {

	text-align: center;
	font-weight: bold;

}

.big {

   font-size: 350%;

}

.ookii {

   font-size: 210%;

}

.full_screen {

   font-size: 270%; 
   
}

.lefter {

font-size: 75%;

}

.big_card {

	font-size: 400%;	
}

.whiter {

    background-color: white;
	
}

.card{

   margin-bottom: 170px;
 
 }


.chiisai{

   font-size: 50%;
 
 } 

  
div.square {
  
  width: 80px;
  height: 80px;
  background-color:red;
  display: block;
  margin-left: auto;
  margin-right: auto;
}

.particle {

	font-weight: normal;

}

.black_background {

	background-color:black;
	padding-left: 10px;
	padding-right: 10px;

}

#gram {

	padding-top: 40px;

}

#kilogram {

	padding-top: 70px;

}

#ton{

	padding-top: 100px;

}

.white {

	color: white;
	
}

.black {

	color: black;
	
}

</style>
</head>
<body class="centered_bold">

<%= @definition.content.to_s.html_safe %>

</body>

app/views/emoquestions/failed.html.erb
<div class='main_div'>

<div class=''>
</div>


<div class='bigger2'>
<p>
  
<p>


<%= params[:cats] %>
</p>

<%= params[:message].to_s.html_safe %>

<br>

<%= link_to 'Next', emoquestion_path(params[:next_question_id], :score => params[:score]) %> 
   
</p>
</div>

app/views/emoquestions/index.html.erb
<h1>List of all questions</h1>
 
<table>
  <tr>
    <th>Question</th>
    <th>Is correct ?</th>
  </tr>
 
  <% @emoquestions.each do |emoquestion| %>
    <tr>
      <td><%= emoquestion.question %></td>
      <td><%= emoquestion.is_correct %></td>
      <td><%= link_to 'Show', emoquestion_path(emoquestion) %></td>
    </tr>
  <% end %>
</table>

app/views/emoquestions/new.html.erb
<%= form_with scope: :emoquestion, url: emoquestions_path, local: true do |form| %>
  <p>
    <%= form.label :question %><br>
    <%= form.text_field :question %>
  </p>
 

  <p>
    <%= form.label :is_correct %><br>
    <%= form.text_area :is_correct %>
  </p>


 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/emoquestions/show.html.erb
<div class='main_div'>

<div class='blank_top'>
</div>


<div class='bigger'>
<p>
  
  <!-- 猫はネズミを食べる -->
  <%= @emoquestion.question.to_s.html_safe %>
  
</p>
</div>

<div class='blank_top'>
</div>


<div  class='big'>

<p>
<table align="center">
  <tr>
    <th><%= form_with scope: :emoquestion, url: check_emoquestion_path, local: true do |form| %>
  <%= form.button  :正 , class: "button499",  name: "emoquestio", value: "1"%>
<%= form.hidden_field :question_id, :value => @emoquestion.id %>
<%= form.hidden_field :question_body, :value => @emoquestion.question.to_s.html_safe %>
<%= form.hidden_field :answer, :value => 1 %>
<%= form.hidden_field :score, :value => params[:score] %>
<% end %> </th>
<th>
	<span class="white">-----</span>

</th>
    <th><%= form_with scope: :emoquestion, url: check_emoquestion_path, local: true do |form| %>
   <%= form.button  :僻 , class: "button499", name: "emoquestio", value: "0" %>
   <%= form.hidden_field :question_id, :value => @emoquestion.id %>
   <%= form.hidden_field :question_body, :value => @emoquestion.question.to_s.html_safe %>
<%= form.hidden_field :answer, :value => 0 %>
<%= form.hidden_field :score, :value => params[:score] %>
<% end %>
	
</th>

  </tr>
</table>

</p>
</div>

app/views/emoquestions/success.html.erb
<p>
You succeeded. Congrats.
<br>
Next
</p>
<td><%= link_to 'Show', emoquestion_path(@next_question_id ) %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>